service: aws-node-api-ok
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sendResponse:
    handler: api/handler.sendResponse
    events:
      - httpApi:
          path: /handlers/results
          method: post
          request:
            schemas:
              application/json:${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/handler.getResult
    events:
      - httpApi:
          path: /handlers/results/{id}
          method: get
          request:

plugins:
  - serverless-offline
